### ISSUE TITLE
Doctrine call MongoCursor::rewind when I try get singleResult from Query

### ISSUE THREAD

**Issue by vsychov** [doctrine/mongodb#219]
Hi, I found some strange issue, when I try to get single record from DB, by code:

``` php
$this
    ->createQueryBuilder()
    ->field('field1')->equals('value1')
    ->getQuery()
    ->getSingleResult();
```

then Cursor::toArray, convert cursor to array by iterator_to_array, and iterator_to_array call MongoCursor::rewind (it's not good for perfomance).

If I call findOneBy, MongoCursor::rewind not called.

**Comment by jmikola** [comment]
Do you have evidence that the query is actually being executed multiple times? Or is the concern just that we're invoking a couple of extra cursor methods?

[`Cursor::getSingleResult()`](https://github.com/doctrine/mongodb/blob/91461ef9ef1b18a3b834767207bbef5481337de3/lib/Doctrine/MongoDB/Cursor.php#L307) does *reset* the cursor before and after executing it, but `rewind()` should only be called once. The `iterator_to_array()` behavior should be no different than iterating with `foreach` and breaking after the first iteration, since we're limiting the reset set to one document.

At the driver level, ['MongoCursor::findOne()`](https://github.com/mongodb/mongo-php-driver/blob/071165f6053b4b6945fe0bdd370d958d62c5c49a/collection.c#L1352) is effectively doing the same thing as [`MongoCursor::rewind()`](https://github.com/mongodb/mongo-php-driver/blob/071165f6053b4b6945fe0bdd370d958d62c5c49a/cursor.c#L1001), followed by `valid()` and `current()`.

Doctrine MongoDB's query builder works against a cursor, which allows it work nicely with the cursor provided for ODM (when hydration is required). For that reason, we don't have a code path that shortcuts to `MongoCollection::findOne()`.
