### ISSUE TITLE
Consulta de datos MongoDB

### ISSUE THREAD

**Issue by 3jFernando** [doctrine/mongodb#259]
Me gustaria saber como ago esto en mongoDB;

en SQL
SELECT * FROM usuarios AS u INNER JOIN tipos_usuarios AS tu ON u._id = tu._id_tipo_usuario

 en MongoDB como seria?.....

se que no hay relaciones en mongo pero como haria algo asi como el ejemplo que puse

**Comment by malarzm** [comment]
@3jFernando please use English, I for one don't know Spanish. But from looks of your question it seems to be not connected with library itself but usage of Mongo so I'd propose posting your problem on StackOverflow or asking on IRC as these are the proper channels to seek guidance.

**Comment by jmikola** [comment]
Since this question isn't relevant to Doctrine, you would do better to use one of the [MongoDB community support](https://docs.mongodb.org/manual/support/#community-support) channels.

With a cursory search, I found numerous Stack Overflow questions pertaining to inner join-like queries in MongoDB. For example:

 * http://stackoverflow.com/q/3829638
 * http://stackoverflow.com/q/2350495

Since those are a bit old, I should note that MongoDB 3.2 added a method to do outer joins via the aggregation frameworks [`$lookup`](https://docs.mongodb.org/manual/reference/operator/aggregation/lookup/) operator. That said, you are better off handling this without the use of that operator if possible.
