### ISSUE TITLE
MongoCursor:$timeout doesn't seem to work for schema:update

### ISSUE THREAD

**Issue by tomekwlod** [doctrine/mongodb#261]
Hello,

I was trying to increase the timeout for MongoCursor when doing schema:update, but an additional parameter --timeout=ms for this command doesn't seem to work at all. 
I was following the logic and I found that for some reason _convertSocketTimeout_ method unsets timeout variable (which causes the issue).

So at the end there is no way that I can change MongoCursor:$timeout for doctrine:mongodb:schema:update event with the parameter --timeout. 

For me, getting rid of the _unset($options['timeout'])_ line within Doctrine\MongoDB\Collection did the trick:

    protected function convertSocketTimeout(array $options)
    {
        if (isset($options['timeout']) && ! isset($options['socketTimeoutMS'])) {
            $options['socketTimeoutMS'] = $options['timeout'];
    //        unset($options['timeout']);
        }

        return $options;
    }

What do you think about that? 

My env:
- driver mongodb v1.1.6
- mongo v3.2
- sumfony v2.8.4

**Comment by malarzm** [comment]
As far as I can tell `timeout` was deprecated in legacy driver since version 1.4 and `socketTimeoutMS` is the way to go for read/write operations. 

Since you've mentioned using new driver, which adapter are you using? Asking since maybe it's an issue somewhere in there

**Comment by alcaeus** [comment]
@malarzm just beat me to the punch. Since you are using the mongodb driver, may I assume that you are also using mongo-php-adapter?

**Comment by tomekwlod** [comment]
Yeah, I think I get it. I didn't expect/realise that I'm probably using wrong (deprecated) adapter (see my configuration below). As I saw on your commits, everything should be sorted out, and I should be able to simply use --timeout parameter for the update command, or setting the timeout as an option to my Cursor or Collection (eg. for counting). But as I said, it doesn't work as it's supposed to. Wrong adaptor can probably explain why.

mongofill/mongofill: dev-master
along with...
doctrine/mongodb: 1.3.0
doctrine/mongodb-odm: 1.0.5

Any suggestions? Thanks a lot

**Comment by alcaeus** [comment]
Looking at mongofill/mongofill, its version constant says `1.3.0-mongofill`. I remember that a while back it was lacking a couple of methods introduced in newer drivers. Since doctrine/mongodb requires `ext-mongo` 1.5 or newer, you really shouldn't use mongofill.

Are you running on PHP 7 or HHVM by any chance? If so, you can check out [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter) (yes, it's a shameless plug for my library). It builds on the 1.6 API and we support it in the sense that we run PHP 7 tests for doctrine/mongodb and ODM in travis-ci with it.

If you are not running on PHP 7 or HHVM, I'd recommend installing the newest `ext-mongo` driver. It won't conflict with `ext-mongodb` you already have installed but is the driver we officially support for now.

**Comment by tomekwlod** [comment]
Unfortunately we are not using either PHP7 or HHVM just yet. But as far as I see now (and not only because of the mongo drivers, adapters, etc), we will have to switch to the newest versions at some point. Sooner than I thought.

But for now it's not possible... So do you suggest to drop mongofill/mongofill and start using alcaeus/mongo-php-adapter (which will serve me ext-mongo: v1.6.13 ??)

**Comment by alcaeus** [comment]
Since you are not using PHP 7 or HHVM I would recommend you use `ext-mongo` and not a polyfill. Once you are planning to move to PHP 7 or HHVM, switch over to a polyfill and start testing with that.

If you really, really want to use a polyfill, don't use mongofill as it's API is too old for doctrine/mongodb and the upcoming ODM release.

Having said all of this, the reason why I asked is simple: the new mongodb driver dropped support for the `timeout` option in cursors as @jmikola mentioned here: https://github.com/alcaeus/mongo-php-adapter/issues/57#issuecomment-187564881.

**Comment by tomekwlod** [comment]
OK I think I know enough now. I am still not sure how I can use no polyfill but just ext-mongo in my app so I will probably push the idea of upgrading the system to work with PHP7, so I can use alcaeus/mongo-php-adapter and other things.

Thanks a lot for your help.

**Comment by alcaeus** [comment]
You don't need a polyfill. You need a polyfill when your system does not support `ext-mongo` (note: no `db` at the end). The only systems where this is the case are HHVM and PHP 7, where this legacy driver will not work. On those systems you can use mongofill (which uses the C driver) or mongo-php-adapter (which uses the new extension, `ext-mongodb`).

On a PHP 5.x system simply install `ext-mongo` and you're good to go: `pecl install mongo`

**Comment by tomekwlod** [comment]
Ah I see. I understand now. Thank you very much for your help. I believe above conversation can help other people as well. 

I think we're fine to close the issue?

Thanks again!

**Comment by alcaeus** [comment]
You're quite welcome. It's a bit confusing at the moment with the drivers, but we'll manage :)
