### ISSUE TITLE
ext-mongo requirement make problems

### ISSUE THREAD

**Issue by prolic** [doctrine/mongodb#269]
we have in https://github.com/alcaeus/mongo-php-adapter 's composer.json:

    "provide": {
        "ext-mongo": "1.6.13"
    },

However, having doctrine/mongodb and alcaeus/mongo-php-adapter as dependency in a project, leads to:

- doctrine/mongodb 1.3.0 requires ext-mongo ^1.5 -> the requested PHP extension mongo is missing from your system.

tested with PHP 7.0.8 and ext-mongodb

**Comment by alcaeus** [comment]
That is due to composer/composer#5030. Please add a composer requirement to `ext-mongo` to your root composer.json as indicated in the [installation instructions](https://github.com/alcaeus/mongo-php-adapter#installation). If you have more issues, please open a ticket against alcaeus/mongo-php-adapter as this is not a problem with this library.

**Comment by cithukyaw** [comment]
I got this error for PHP 5.6.

> doctrine/mongodb 1.3.0 requires ext-mongo ^1.5 -> the requested PHP extension mongo is missing from your system.

**Comment by alcaeus** [comment]
Do you have the mongo extension installed? if so, which version?

**Comment by cithukyaw** [comment]
Installing [the deprecated MongoDB driver](http://pecl.php.net/package/mongo) solved the error.  [The recommended driver](http://pecl.php.net/package/mongodb) did not work for PHP 5.6

**Comment by alcaeus** [comment]
The recommended driver is ext-mongodb and replaces ext-mongo, which is now known as the legacy driver. This library has not been rewritten to work with the old driver, hence the requirement to ext-mongo.

**Comment by manuelbcd** [comment]
@alcaeus In our profiling tool the adapter was up to 3x times slower than the legacy driver (mongoc).  Is it a misconfiguration from our side? Do you have information about performance?  Thanks in advance

**Comment by alcaeus** [comment]
@manuelbcd No, that's to be expected. I've detailed this in https://github.com/alcaeus/mongo-php-adapter/issues/124#issuecomment-236675167, but there's nothing I can do at this time. If you are using MongoDB ODM, you'll have to deal with the drop in performance until we release 2.0 (which builds on ext-mongodb and is expected later this year).

If you are not using Doctrine MongoDB ODM, you should be using `mongodb/mongodb` instead of `doctrine/mongodb` ;)

**Comment by manuelbcd** [comment]
@alcaeus  Thanks for your answer. Yes I'm using doctrine mongodb ODM.  I will have to wait for the release planned for this year.  Are there any chance to get involved with this doctrine release?
