### ISSUE TITLE
Error: the match filter must be an expression in an object

### ISSUE THREAD

**Issue by olvlvl** [doctrine/mongodb#305]
Hi,

```php
$documentManager
    ->getDocumentCollection(Cuisine::class)
    ->aggregate([
        [ '$match' => [] ],
    ]);
```

Throws `Doctrine\MongoDB\Exception\ResultException`, while the following command is fine in MongoDB:

```json
db.getCollection('cuisines').aggregate([ { $match: {} }] )
```

Note that `[ '$match' => (object) [] ]` is fine too.

**Comment by jmikola** [comment]
That error appears to come from the server. I quickly verified that it is reported by versions going back to 2.4, so I assume that `aggregate` always required a document (BSON type [`0x03`](http://bsonspec.org/spec.html)) for the `$match` value. 

This doesn't look like a bug in Doctrine MongoDB, as it's passing the value you provide in the command. While the library certainly could inspect the pipeline argument and cast empty arrays for `$match` to an object behind the scenes, that may be a rabbit hole not worth going down as other pipeline operators likely have similar requirements. Note that [mongodb/mongo-php-library](https://github.com/mongodb/mongo-php-library/blob/master/src/Operation/Aggregate.php) also doesn't attempt to inspect the pipeline beyond ensuring that it is an array.

@alcaeus: Does the aggregation builder address this by ensuring an empty query for [`Doctrine/MongoDB/Aggregation/Stage/Match`](https://github.com/doctrine/mongodb/blob/master/lib/Doctrine/MongoDB/Aggregation/Stage/Match.php) serializes as a BSON object?

I realize that this is inconsistent with the server and PHP driver historically allowing an empty array for a find operation's query filter, but `aggregate` was implemented around a point where server commands began to implement stricter type checking for their parameters.

**Comment by alcaeus** [comment]
The aggregation builder would return an empty array, similar to the queries (since they build on the same `Expr` class. Example from a quick unit test:
```
$matchStage = new Match($this->getTestAggregationBuilder());
$this->assertSame(['$match' => []], $matchStage->getExpression());
```

This is something we might have to address in ODM 2.0: always return objects instead of associative arrays. Until then I'm not sure what to do with this. I'd go ahead and argue that using an empty `$match` stage doesn't make a lot of sense since it doesn't do any filtering at all and might as well be omitted.

**Comment by olvlvl** [comment]
I'm doing this for now `'$match' => $match ?: (object) []`.

**Comment by alcaeus** [comment]
@olvlvl May I ask how you manage to get an empty match stage? Are you dynamically building up the aggregation pipeline and end up with an empty `$match` in some cases?

My initial thought was to skip the stage entirely if it's empty, but I believe we may have to change the logic entirely so it does in fact return an empty object instead of an empty array. What do you think @jmikola?

**Comment by olvlvl** [comment]
@alcaeus Yes, I'm building the stage myself in that case, and provide the `$match` value as an argument.

**Comment by jmikola** [comment]
@alcaeus: I didn't get a change to see #307 before you merged, but that solution LGTM.

**Comment by ganpatigarv** [comment]
{ where: { id: "any value" }

**Comment by ganpatigarv** [comment]
{ where: { "id" : "any value"}}
